const userData = [
  {
    id: "01",
    picture: {
      large: "https://randomuser.me/api/portraits/women/22.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/22.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/22.jpg",
    },
    gender: "female",
    name: { title: "Mrs", first: "Sophia", last: "Renard" },
    cellNo: "+91 2542526345",
    email: "sophiaren@gmail.com",
    age: 45,
    surgeryType: "Rotator cuff",
    surgeryDate: "15 Aug 2022",
    height: 163,
    weight: 110,
    bmi: 19,
    doctorName: "Dr.Holland",
    doctorMobile: "+91 8524563987",
    doctorMail: "holland@gmail.com",
  },
  {
    id: "02",
    picture: {
      large: "https://randomuser.me/api/portraits/women/23.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/23.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/23.jpg",
    },
    gender: "female",
    name: { title: "Mrs", first: "Sia", last: "Lane" },
    cellNo: "+91 2542526024",
    email: "sialane@gmail.com",
    age: 35,
    surgeryType: "Rupture cuff",
    surgeryDate: "01 Aug 2022",
    height: 120,
    weight: 80,
    bmi: 14,
    doctorName: "Dr.Kunai",
    doctorMobile: "+91 8524562479",
    doctorMail: "kunai@gmail.com",
  },
  {
    id: "03",
    picture: {
      large: "https://randomuser.me/api/portraits/men/22.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/22.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/22.jpg",
    },
    gender: "male",
    name: { title: "Mr", first: "Leo", last: "Capricon" },
    cellNo: "+91 2542526345",
    email: "leocapricon@gmail.com",
    age: 55,
    surgeryType: "semi Dermis",
    surgeryDate: "15 Sept 2022",
    height: 143,
    weight: 80,
    bmi: 14,
    doctorName: "Dr.Sakura",
    doctorMobile: "+91 8524564578",
    doctorMail: "sakura@gmail.com",
  },
  {
    id: "04",
    picture: {
      large: "https://randomuser.me/api/portraits/women/20.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/20.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/20.jpg",
    },
    gender: "female",
    name: { title: "Mrs", first: "Serena", last: "Mc" },
    cellNo: "+91 2542526345",
    email: "serenamc@gmail.com",
    age: 50,
    surgeryType: "Pelvis Cuff",
    surgeryDate: "15 Oct 2022",
    height: 180,
    weight: 90,
    bmi: 16,
    doctorName: "Dr.Hima",
    doctorMobile: "+91 0824563987",
    doctorMail: "hima@gmail.com",
  },
  {
    id: "05",
    picture: {
      large: "https://randomuser.me/api/portraits/men/20.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/20.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/20.jpg",
    },
    gender: "male",
    name: { title: "Mr", first: "Zen", last: "Dextrus" },
    cellNo: "+91 2542526345",
    email: "zendextrus@gmail.com",
    age: 30,
    surgeryType: "Repo Nostril",
    surgeryDate: "1 Jan 2022",
    height: 155,
    weight: 65,
    bmi: 20,
    doctorName: "Dr.Uzumaki",
    doctorMobile: "+91 085423987",
    doctorMail: "uzumaki@gmail.com",
  },
];
export default userData;
